version: "3.8"
services:

  ### Mysql container
  mysql: 
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MainDB
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes

    volumes:
      - mysql:/var/lib/mysql
    
volumes:
  mysql: